### ISSUE TITLE
handleEnd is called on load

### ISSUE THREAD

**Issue by pearlsrvcs** [LucasBassetti/react-simple-chatbot#116]
## Description

I have implemented the react-native-chatbot and within the steps array, I set end: false on every step except the last one, where it is set to true. Yet, as soon as the ChatBot is loaded, my handleEnd function is called. Any ideas what I can do about this?

**Comment by Cyclodex** [comment]
I don't think that it has to do with the _end: false_ as I have this without issues. (not using react-native)
You could add a breakpoint and check the callstack why your handleEnd is already executed.

Also this issue is in the wrong place for react-native, but you already created an issue there I see: https://github.com/LucasBassetti/react-native-chatbot/issues/31

**Comment by LucasBassetti** [comment]
Please follow the @Cyclodex tip
