### ISSUE TITLE
href links within messages?

### ISSUE THREAD

**Issue by 4rweb** [LucasBassetti/react-simple-chatbot#49]
when I pass an http href inside the text box the chabot does not recognize it as a link! How do I enable the chat to recognize links?

**Comment by LucasBassetti** [comment]
Hi,

You can create a custom component with `asMessage:true`

Example:

```
{
      id: '1',
      component: (
        <div> This is a example component with <a href="some_link">link_text</a> </div>
      ),
      asMessage: true,
      trigger: '2'
}
```

**Comment by christianortega123** [comment]
So in your DBpedia example, you're rendering a DBpedia component. I wrote code that responds to questions input by the user, but some of those answers have links in them. I'm rending all of my steps exactly as your have it in your DBpedia example in your documentation, so I can't see a way I could get the bot to render a link from within the DBpedia class. Is there a workaround? Thank you!! Your bot is awesome!

**Comment by Cyclodex** [comment]
What is your problem exactly? You can simply put a link as content to render, and it should work.
If not, what does it look like or what is the problem exactly?

It should work as @LucasBassetti  stated above. I have an other example here which will do it with a custom component, but as its own react component and using the **metadata** object:

For example the following **custom component**, which renders finally:
```
class OpenLink extends Component {
    constructor(props) {
        super(props);
    }
    render() {
        const link = this.props.step.metadata.link || '';
        const text = this.props.step.metadata.text || '';
        return (
            <a href={link} target="_blank">
                {text}
            </a>
        );
    }
}
```
and I call this Component (OpenLink) like that from the steps:
```
{
  id: 'link',
  asMessage: true,
  component: <OpenLink />,
  metadata: {
    link: 'YOUR_LINK',
    text: 'YOUR LINK TEXT',
  },
  trigger: '...',
},
```

**Comment by christianortega123** [comment]
Hi @Cyclodex !

So here's what I'm trying to do.

![screen shot 2018-08-08 at 1 39 49 pm](https://user-images.githubusercontent.com/22563806/43863610-17033712-9b12-11e8-9330-1afae6a73736.png)

Basically, DBPedia is a class that lets you ask a question and have the bot spit out an answer to that question (answer is stored in a variable called `finalAnswer`. DBPedia has a state called `result`, which I use in the following way:
`            self.setState({result: finalAnswer});
`

`finalAnswer` is simply a string that is returned from a handler function. Some of my answers (which are strings) have hyperlinks in them, like this one:

`  displayApps: [
    'Looks like you want to see your apps. Here is a ' +  'https://testlink.com/' + 'to your apps.',
  ]`

The result of doing all of this is the bot replying: 

"Looks like you want to see your apps. Here is a https://testlink.com/ to your apps., where https://testlink.com is NOT a hyperlink. I'm trying to see how to use a custom component to make this a hyperlink since that seems to be the only way to do this, but I'm having a bit of trouble.

Thanks!

**Comment by Cyclodex** [comment]
Yea, but this is just a URL in a string right? There is no markup for displaying a link?!
Your message should of course contain a real link, like this:
`<a href="https://testlink.com/">https://testlink.com/</a>`

Or do I understand something wrong here ? :)

**Comment by christianortega123** [comment]
@Cyclodex thanks! I was actually doing this and meant to write it that way in my post:

`displayApps: [ 'Looks like you want to see your apps. Here is a ' + <a href="https://testlink.com/">https://testlink.com/</a> + 'to your apps.', ]`

When I wrote it this way it literally displayed the everything above. I don't know why I thought this concatenation would work without having a body tag. I fixed it by doing this:

  
`<body>Looks like you want to see your apps. Here is a <a href="https://google.com/">link</a>to your apps</body>`

Silly mistake. Thanks for helping!
